#!/bin/sh

echo $GIT_REFLOG_ACTION

KERNEL_NAME=$(uname -s);
if [ "$KERNEL_NAME" = "Darwin" ]; then
    PLAYER="afplay"
else
    PLAYER="mplayer"
fi

if [ "$GIT_REFLOG_ACTION" != pull ]; then
    branch=`git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`
    if [ "$branch" = master ]; then
        ($PLAYER ~/lib/FinalFantasyVictory.mp3 &) > /dev/null 2>&1
    fi
fi
